(()=>{'use strict';
const DEFAULTS=[
{id:'mira',name:'聖虚ミラージュ',reading:'セントホロミラージュ',series:'',type:'人型',gender:'男性',count:'単体',subject:'',tags:[],image:null,order:1},
{id:'tenpen',name:'天変ストム',reading:'テンペンストム',series:'ストム',type:'人型',gender:'女性',count:'単体',subject:'自然現象',tags:['雷','虹'],image:'./tenpen.jpeg',order:2},
{id:'meiryu',name:'溟流ストム',reading:'メイルストム',series:'ストム',type:'人型',gender:'',count:'単体',subject:'自然現象',tags:['海','生命'],image:'./meiryu.jpeg',order:3},
{id:'seibou',name:'曐暴ストム',reading:'スタバーストム',series:'ストム',type:'人型',gender:'',count:'単体',subject:'宇宙',tags:['銀河'],image:'./seibou.jpeg',order:4},
{id:'mandala',name:'曼荼羅BROS',reading:'',series:'',type:'人型',gender:'',count:'複数',subject:'抽象・概念',tags:['曼荼羅'],image:null,order:5},
{id:'eikun',name:'睿君リプス',reading:'エイクンリプス',series:'',type:'人型',gender:'男性',count:'単体',subject:'光・影',tags:['蝕'],image:null,order:6},
{id:'slot',name:'スロット・エモット',reading:'',series:'',type:'人型',gender:'女性',count:'単体',subject:'',tags:['三眼'],image:null,order:7},
{id:'arosa',name:'未黎アローザ／末黎アローザ',reading:'ミクロアローザ／マクロアローザ',series:'',type:'動物',gender:'',count:'単体',subject:'抽象・概念',tags:['黒猫'],image:null,order:8},
{id:'mary',name:'久織屋メアリ',reading:'',series:'',type:'人型',gender:'女性',count:'単体',subject:'色・知覚',tags:['加法混色'],image:null,order:9},
{id:'tikitira',name:'ティキティラ-M',reading:'',series:'',type:'その他',gender:'',count:'単体',subject:'次元・機械',tags:['11次元'],image:null,order:10}
];
const CORE_AXES=['gender','type','count','subject','series']; const AXIS_LABEL={gender:'性別',type:'種別',count:'人数',subject:'表現対象',series:'シリーズ'};
let db,stickers=[],axes=[],visible=[],currentId=null,editingId=null,sortMode='order',filters={}; let gesture={x:0,y:0,depth:1}; let formDirty=false,saveTimer=null;
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll('.screen')]; const show=id=>{screens.forEach(x=>x.classList.toggle('active',x.id===id));};
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open('hololab-db',1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains('stickers'))d.createObjectStore('stickers',{keyPath:'id'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});};q.onsuccess=()=>{db=q.result;res()};q.onerror=()=>rej(q.error)})}
const tx=(store,mode='readonly')=>db.transaction(store,mode).objectStore(store); const getAll=s=>new Promise((r,j)=>{const q=tx(s).getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)}); const put=(s,v)=>new Promise((r,j)=>{const q=tx(s,'readwrite').put(v);q.onsuccess=()=>r();q.onerror=()=>j(q.error)}); const del=(s,k)=>new Promise((r,j)=>{const q=tx(s,'readwrite').delete(k);q.onsuccess=()=>r();q.onerror=()=>j(q.error)});
async function seed(){stickers=await getAll('stickers');if(!stickers.length){for(const s of DEFAULTS)await put('stickers',s);stickers=await getAll('stickers')}const m=await new Promise(r=>{const q=tx('meta').get('axes');q.onsuccess=()=>r(q.result)});axes=m?.value||CORE_AXES.map(k=>({key:k,label:AXIS_LABEL[k]}));}
function apply(){const q=$('#search').value.trim().toLowerCase();visible=stickers.filter(s=>{const text=[s.name,s.reading,s.series,s.type,s.gender,s.count,s.subject,...(s.tags||[])].join(' ').toLowerCase();if(q&&!text.includes(q))return false;return Object.entries(filters).every(([k,v])=>!v||String(s[k]||'')===v)});visible.sort(sortMode==='name'?(a,b)=>a.name.localeCompare(b.name,'ja'):(a,b)=>(a.order||0)-(b.order||0));renderGrid()}
function renderGrid(){const g=$('#grid');g.innerHTML='';visible.forEach(s=>{const b=document.createElement('button');b.className='tile';b.innerHTML=`<div class="thumb">${s.image?`<img src="${s.image}">`:'<span class="placeholder">?</span>'}</div><b>${s.name}</b><small>${s.reading||s.series||'COMING SOON'}</small>`;b.onclick=()=>openViewer(s.id);g.append(b)})}
function filterUI(){const p=$('#filterPanel');p.innerHTML='';axes.forEach(a=>{const vals=[...new Set(stickers.map(s=>s[a.key]).filter(Boolean))].sort();const row=document.createElement('div');row.className='filterRow';row.innerHTML=`<b>${a.label}</b><select data-axis="${a.key}"><option value="">ALL</option>${vals.map(v=>`<option ${filters[a.key]===v?'selected':''}>${v}</option>`).join('')}</select>`;row.querySelector('select').onchange=e=>{filters[a.key]=e.target.value;apply()};p.append(row)})}
function openViewer(id){apply();currentId=id;const s=stickers.find(x=>x.id===id);if(!s)return;$('#viewName').textContent=s.name;$('#viewSub').textContent=s.reading||s.series||'';document.querySelectorAll('.card').forEach((c,i)=>{const im=c.querySelector('img');c.classList.toggle('empty',!s.image);if(s.image){im.src=s.image;im.style.display='block'}else{im.removeAttribute('src');im.style.display='none'}});show('viewer');updateNav()}
function updateNav(){const i=visible.findIndex(s=>s.id===currentId);$('#prev').disabled=i<=0;$('#next').disabled=i<0||i>=visible.length-1}
function nav(d){const i=visible.findIndex(s=>s.id===currentId),n=visible[i+d];if(n)openViewer(n.id)}
function renderEditList(){const a=$('#editList');a.innerHTML='';stickers.slice().sort((x,y)=>(x.order||0)-(y.order||0)).forEach(s=>{const b=document.createElement('button');b.className='editItem'+(s.id===editingId?' sel':'');b.textContent=s.name;b.onclick=()=>loadForm(s.id);a.append(b)})}
function loadForm(id){editingId=id;const s=stickers.find(x=>x.id===id);if(!s)return;for(const [k,el] of [['name','fName'],['reading','fReading'],['series','fSeries'],['type','fType'],['gender','fGender'],['count','fCount'],['subject','fSubject']])$('#'+el).value=s[k]||'';$('#fTags').value=(s.tags||[]).join(', ');$('#fImage').value='';setSavedState(false);renderEditList();renderAxes()}
function renderAxes(){const a=$('#axes');a.innerHTML='';axes.forEach(x=>{const d=document.createElement('div');d.className='axis';d.innerHTML=`<span>${x.label}</span>${CORE_AXES.includes(x.key)?'':`<button data-k="${x.key}">REMOVE</button>`}`;a.append(d)});a.querySelectorAll('button').forEach(b=>b.onclick=async()=>{axes=axes.filter(x=>x.key!==b.dataset.k);await put('meta',{key:'axes',value:axes});renderAxes();filterUI()})}
function setSavedState(dirty,flash=false){formDirty=dirty;const b=$('#saveBtn'),st=$('#saveState');if(!b||!st)return;b.classList.toggle('dirty',dirty);b.classList.toggle('flash',flash);st.className='saveState '+(dirty?'dirty':'saved')+(flash?' flash':'');st.textContent=dirty?'UNSAVED CHANGES ●':(flash?'SAVED ✓':'SAVED ✓');if(saveTimer)clearTimeout(saveTimer);if(flash)saveTimer=setTimeout(()=>{b.classList.remove('flash');st.classList.remove('flash')},1600)}
function normalizeOrder(){stickers.slice().sort((a,b)=>(a.order||0)-(b.order||0)).forEach((s,i)=>s.order=i+1)}
async function moveEditing(dir){const ordered=stickers.slice().sort((a,b)=>(a.order||0)-(b.order||0)),i=ordered.findIndex(s=>s.id===editingId),j=i+dir;if(i<0||j<0||j>=ordered.length)return;const a=ordered[i],b=ordered[j],o=a.order;a.order=b.order;b.order=o;await put('stickers',a);await put('stickers',b);stickers=await getAll('stickers');renderEditList();apply();setSavedState(false,true)}
async function fileData(file){return new Promise((r,j)=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.onerror=j;fr.readAsDataURL(file)})}
$('#form').onsubmit=async e=>{e.preventDefault();let s=stickers.find(x=>x.id===editingId);if(!s)return;for(const [k,el] of [['name','fName'],['reading','fReading'],['series','fSeries'],['type','fType'],['gender','fGender'],['count','fCount'],['subject','fSubject']])s[k]=$('#'+el).value.trim();s.tags=$('#fTags').value.split(',').map(x=>x.trim()).filter(Boolean);const f=$('#fImage').files[0];if(f)s.image=await fileData(f);await put('stickers',s);stickers=await getAll('stickers');apply();renderEditList();$('#fImage').value='';setSavedState(false,true)};
$('#moveUp').onclick=()=>moveEditing(-1);$('#moveDown').onclick=()=>moveEditing(1);['#fName','#fReading','#fSeries','#fType','#fGender','#fCount','#fSubject','#fTags','#fImage'].forEach(sel=>{$(sel).addEventListener(sel==='#fImage'?'change':'input',()=>setSavedState(true))});
$('#newSticker').onclick=async()=>{const id='sticker-'+Date.now();const s={id,name:'NEW STICKER',reading:'',series:'',type:'',gender:'',count:'',subject:'',tags:[],image:null,order:Math.max(0,...stickers.map(x=>x.order||0))+1};await put('stickers',s);stickers=await getAll('stickers');loadForm(id);apply()};
$('#addAxis').onclick=async()=>{const label=$('#newAxis').value.trim();if(!label)return;const key='axis_'+Date.now();axes.push({key,label});stickers.forEach(s=>s[key]='');await put('meta',{key:'axes',value:axes});$('#newAxis').value='';renderAxes();filterUI()};
$('#exportAll').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,axes,stickers},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HOLO_LAB_BACKUP.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importAll').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d.stickers))throw 0;for(const s of d.stickers)await put('stickers',s);axes=Array.isArray(d.axes)?d.axes:axes;await put('meta',{key:'axes',value:axes});stickers=await getAll('stickers');apply();filterUI();renderEditList();alert('IMPORT COMPLETE')}catch(_){alert('IMPORT FAILED')}e.target.value=''};
$('#search').oninput=apply;$('#sortBtn').onclick=()=>{sortMode=sortMode==='order'?'name':'order';$('#sortBtn').textContent='SORT: '+(sortMode==='order'?'ORDER':'NAME');apply()};$('#filterBtn').onclick=()=>{$('#filterPanel').classList.toggle('hidden');filterUI()};$('#editOpen').onclick=()=>{show('editor');editingId=stickers.slice().sort((a,b)=>(a.order||0)-(b.order||0))[0]?.id;renderEditList();if(editingId)loadForm(editingId)};$('#editClose').onclick=()=>{apply();show('collection')};$('#back').onclick=()=>show('collection');$('#prev').onclick=()=>nav(-1);$('#next').onclick=()=>nav(1);$('#reset').onclick=()=>{gesture={x:0,y:0,depth:1};$('#status').textContent='RESET / 外側スワイプ＝ホロ操作 / ピンチ＝視点遠近'};
// Common input channel. Sticker cards themselves ignore pointer input; use surrounding viewer area.
let pointers=new Map(),startOne=null,startDist=null,startDepth=1;const zone=$('#gestureZone');
function outsidePair(t){return !t.closest?.('#pair')}
zone.addEventListener('pointerdown',e=>{if(!outsidePair(e.target))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});zone.setPointerCapture(e.pointerId);if(pointers.size===1)startOne={x:e.clientX,y:e.clientY,gx:gesture.x,gy:gesture.y};if(pointers.size===2){const p=[...pointers.values()];startDist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);startDepth=gesture.depth}},true);
zone.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&startOne){gesture.x=startOne.gx+(e.clientX-startOne.x)/180;gesture.y=startOne.gy+(e.clientY-startOne.y)/180;$('#status').textContent=`HOLO INPUT x ${gesture.x.toFixed(2)} / y ${gesture.y.toFixed(2)}`}else if(pointers.size===2&&startDist){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);gesture.depth=Math.max(.35,Math.min(2.8,startDepth*d/startDist));$('#status').textContent=`VIEW DEPTH ${gesture.depth.toFixed(2)} / シールサイズ固定`}},true);
function up(e){pointers.delete(e.pointerId);if(pointers.size<2)startDist=null;if(!pointers.size)startOne=null}zone.addEventListener('pointerup',up,true);zone.addEventListener('pointercancel',up,true);
$('#start').onclick=async()=>{try{if(typeof DeviceOrientationEvent?.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')return;$('#start').textContent='TILT ACTIVE';$('#status').textContent='TILT ACTIVE / 外側操作も使用可'}catch(_){}};
(async()=>{await openDB();await seed();apply();filterUI();renderEditList()})().catch(e=>{console.error(e);$('#grid').innerHTML='<p>LOCAL DATABASE ERROR</p>'});
})();
