(()=>{const C=[left,right];let x=0,y=0,d=0,lx=0,ly=0;const T=Math.PI*2,cl=(v,a,b)=>Math.max(a,Math.min(b,v)),fr=v=>v-Math.floor(v);
function col(h){h=fr(h)*6;let i=h|0,f=h-i,p=.08,q=1-.92*f,t=.08+.92*f,c=[[1,t,p],[q,1,p],[p,1,t],[p,q,1],[t,p,1],[1,p,q]][i%6];return`rgb(${c[0]*255|0},${c[1]*255|0},${c[2]*255|0})`}
function rot(p){let[X,Y,Z]=p,cy=Math.cos(x*.82),sy=Math.sin(x*.82),x1=cy*X+sy*Z,z1=-sy*X+cy*Z,cx=Math.cos(y*.62),sx=Math.sin(y*.62);return[x1,cx*Y-sx*z1,sx*Y+cx*z1]}
function pr(p,w,h,e){let z=p[2]+3.15,f=Math.min(w,h)*1.12;return[w/2+(p[0]+e*.032)*f/z,h/2-p[1]*f/z]}
let seed=17321,R=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646},pts=[];for(let i=0;i<300;i++){let X,Y,Z;do{X=R()*1.42-.71;Y=R()*1.42-.71;Z=R()*1.42-.71}while(X*X+Y*Y+Z*Z>.49);let u=R();pts.push({p:[X,Y,Z],s:u<.82?0:u<.97?1:2,h:(R()*8)|0,ph:R()*T,r:R()})}
let spr=[];for(let h=0;h<8;h++){spr[h]=[];for(let s=0;s<3;s++){let n=[5,7,10][s],c=document.createElement('canvas');c.width=c.height=n*4;let g=c.getContext('2d'),r=c.width/2,gr=g.createRadialGradient(r,r,0,r,r,r);gr.addColorStop(0,'white');gr.addColorStop(.18,col(h/8));gr.addColorStop(1,'rgba(255,255,255,0)');g.fillStyle=gr;g.fillRect(0,0,c.width,c.height);spr[h][s]=c}}
let m=document.createElement('canvas');m.width=220;m.height=270;let mg=m.getContext('2d');mg.fillStyle='white';mg.font='900 230px Arial Black,Arial';mg.textAlign='center';mg.textBaseline='middle';mg.fillText('?',110,126);
function draw(c,e,t){let g=c.getContext('2d',{alpha:false,desynchronized:true}),r=Math.min(devicePixelRatio||1,1.5),w=c.clientWidth*r|0,h=c.clientHeight*r|0;if(c.width!=w||c.height!=h){c.width=w;c.height=h}g.fillStyle='#050507';g.fillRect(0,0,w,h);g.save();g.globalCompositeOperation='lighter';for(let a of pts){let p=pr(rot(a.p),w,h,e),rare=Math.pow(Math.max(0,Math.sin(t*(.22+a.r*.25)+a.ph*2.2)),26),al=.12+.28*(.5+.5*Math.sin(t*(.8+a.r)+a.ph))+rare*.78,im=spr[a.h][a.s],sc=[.58,.72,.9][a.s]*(1+rare*.4),dw=im.width*sc;g.globalAlpha=al;g.drawImage(im,p[0]-dw/2,p[1]-dw/2,dw,dw);if(rare>.72&&a.s==2){let L=5+rare*6;g.globalAlpha=.55*rare;g.strokeStyle='white';g.lineWidth=.7;g.beginPath();g.moveTo(p[0]-L,p[1]);g.lineTo(p[0]+L,p[1]);g.moveTo(p[0],p[1]-L);g.lineTo(p[0],p[1]+L);g.stroke()}}g.restore();
let hue=fr(x*1.65+y*1.1+.12),A=pr(rot([-.73,.88,.15]),w,h,e),B=pr(rot([.73,.88,.15]),w,h,e),D=pr(rot([-.73,-.92,.15]),w,h,e),tc=document.createElement('canvas');tc.width=220;tc.height=270;let tg=tc.getContext('2d');tg.drawImage(m,0,0);tg.globalCompositeOperation='source-in';tg.fillStyle=col(hue);tg.fillRect(0,0,220,270);g.save();g.setTransform((B[0]-A[0])/220,(B[1]-A[1])/220,(D[0]-A[0])/270,(D[1]-A[1])/270,A[0],A[1]);g.drawImage(tc,0,0);g.restore()}
let st=performance.now();function loop(t){draw(C[0],-1,(t-st)/1000);draw(C[1],1,(t-st)/1000);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function set(a,b){x=cl(a,-1,1);y=cl(b,-1,1)}C.forEach(c=>{c.onpointerdown=e=>{d=1;lx=e.clientX;ly=e.clientY};c.onpointermove=e=>{if(!d)return;set(x+(e.clientX-lx)/180,y+(e.clientY-ly)/180);lx=e.clientX;ly=e.clientY};c.onpointerup=()=>d=0});function o(e){if(!d)set((e.gamma||0)/24,(e.beta||0)/24)}async function motion(){try{if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!='granted')return;addEventListener('deviceorientation',o,true);motionBtn.textContent='TILT ACTIVE'}catch(_){}}let motionBtn=document.getElementById('motion');motionBtn.onclick=motion;addEventListener('deviceorientation',o,true)})();