(()=>{
const C=[document.getElementById('left'),document.getElementById('right')];let tx=0,ty=0,x=0,y=0,drag=0,lx=0,ly=0;
function shader(g,t,s){let q=g.createShader(t);g.shaderSource(q,s);g.compileShader(q);return q}function program(g,v,f){let p=g.createProgram();g.attachShader(p,shader(g,g.VERTEX_SHADER,v));g.attachShader(p,shader(g,g.FRAGMENT_SHADER,f));g.linkProgram(p);return p}
const V=`attribute vec3 p;attribute float seed;uniform float rx,ry,eye,pointSize,time;varying float S;void main(){float cx=cos(rx),sx=sin(rx),cy=cos(ry),sy=sin(ry);vec3 a=vec3(cy*p.x+sy*p.z,sx*sy*p.x+cx*p.y-sx*cy*p.z,-cx*sy*p.x+sx*p.y+cx*cy*p.z);float z=a.z+3.0;gl_Position=vec4((a.x+eye)/z*2.45,a.y/z*2.45,(z-1.5)/4.5,1.);S=seed;float flare=pow(max(0.,sin(time*(.45+fract(seed*13.)*.8)+seed*91.)),30.);gl_PointSize=pointSize*(.7+flare*3.2);}`;
const F=`precision mediump float;uniform int mode;uniform float hue,time;varying float S;vec3 H(float t){return .58+.42*cos(6.283185*(vec3(0.,.333,.667)+t));}void main(){if(mode==1){vec2 q=gl_PointCoord-.5;float r=length(q);if(r>.5)discard;float flare=pow(max(0.,sin(time*(.45+fract(S*13.)*.8)+S*91.)),30.);float a=smoothstep(.5,0.,r)*(.25+flare*.75);gl_FragColor=vec4(H(fract(S*.73+hue*.12)),a);return;}gl_FragColor=vec4(H(hue),.96);}`;
function questionPoints(){let a=[],s=[],cv=document.createElement('canvas');cv.width=80;cv.height=100;let g=cv.getContext('2d');g.fillStyle='white';g.font='900 88px Arial Black,Arial';g.textAlign='center';g.textBaseline='middle';g.fillText('?',40,46);let d=g.getImageData(0,0,80,100).data;for(let y=0;y<100;y+=2)for(let x=0;x<80;x+=2)if(d[(y*80+x)*4+3]>100){a.push((x-40)*.013,(50-y)*.013,0);s.push(.2)}return[a,s]}
function inc(){let a=[],s=[],seed=9917,r=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646};for(let k=0;k<420;k++){let X,Y,Z;do{X=r()*1.5-.75;Y=r()*1.5-.75;Z=r()*1.5-.75}while(X*X+Y*Y+Z*Z>.55);a.push(X,Y,Z);s.push(r())}return[a,s]}
let Q=questionPoints(),I=inc();
function setup(c,eye){let g=c.getContext('webgl',{antialias:true}),P=program(g,V,F);g.useProgram(P);let L={p:g.getAttribLocation(P,'p'),s:g.getAttribLocation(P,'seed'),rx:g.getUniformLocation(P,'rx'),ry:g.getUniformLocation(P,'ry'),e:g.getUniformLocation(P,'eye'),ps:g.getUniformLocation(P,'pointSize'),t:g.getUniformLocation(P,'time'),m:g.getUniformLocation(P,'mode'),h:g.getUniformLocation(P,'hue')};function B(a){let b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(a),g.STATIC_DRAW);return b}let qb=[B(Q[0]),B(Q[1])],ib=[B(I[0]),B(I[1])];function attrs(b){g.bindBuffer(g.ARRAY_BUFFER,b[0]);g.enableVertexAttribArray(L.p);g.vertexAttribPointer(L.p,3,g.FLOAT,0,0,0);g.bindBuffer(g.ARRAY_BUFFER,b[1]);g.enableVertexAttribArray(L.s);g.vertexAttribPointer(L.s,1,g.FLOAT,0,0,0)}
return T=>{let d=Math.min(devicePixelRatio||1,2),w=c.clientWidth*d|0,h=c.clientHeight*d|0;if(c.width!=w||c.height!=h){c.width=w;c.height=h}g.viewport(0,0,w,h);g.clearColor(.006,.006,.009,1);g.clear(g.COLOR_BUFFER_BIT);g.enable(g.BLEND);g.uniform1f(L.rx,y*.65);g.uniform1f(L.ry,x*.8);g.uniform1f(L.e,eye*.035);g.uniform1f(L.t,T);g.uniform1f(L.h,((x*1.7+y*1.1)%1+1)%1);attrs(qb);g.uniform1i(L.m,0);g.uniform1f(L.ps,5*d);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.drawArrays(g.POINTS,0,Q[0].length/3);attrs(ib);g.uniform1i(L.m,1);g.blendFunc(g.SRC_ALPHA,g.ONE);g.uniform1f(L.ps,1.05*d);g.drawArrays(g.POINTS,0,I[0].length/3);g.uniform1f(L.ps,1.75*d);g.drawArrays(g.POINTS,0,Math.floor(I[0].length/3*.13));}}
let D=[setup(C[0],-1),setup(C[1],1)],st=performance.now();function loop(t){x+=(tx-x)*.1;y+=(ty-y)*.1;D.forEach(f=>f((t-st)/1000));requestAnimationFrame(loop)}requestAnimationFrame(loop);
C.forEach(c=>{c.onpointerdown=e=>{drag=1;lx=e.clientX;ly=e.clientY};c.onpointermove=e=>{if(!drag)return;tx=Math.max(-1,Math.min(1,tx+(e.clientX-lx)/180));ty=Math.max(-1,Math.min(1,ty+(e.clientY-ly)/180));lx=e.clientX;ly=e.clientY};c.onpointerup=()=>drag=0});function o(e){if(!drag){tx=Math.max(-1,Math.min(1,(e.gamma||0)/24));ty=Math.max(-1,Math.min(1,(e.beta||0)/24))}}async function motion(){try{if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!='granted')return;addEventListener('deviceorientation',o,true);document.getElementById('motion').textContent='TILT ACTIVE'}catch(e){}}document.getElementById('motion').onclick=motion;addEventListener('deviceorientation',o,true);
})();